# Generated by Django 6.0.3 on 2026-03-17 10:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bike',
            name='image',
        ),
        migrations.RemoveField(
            model_name='bike',
            name='location',
        ),
        migrations.RemoveField(
            model_name='bike',
            name='seller_name',
        ),
        migrations.RemoveField(
            model_name='bike',
            name='seller_phone',
        ),
        migrations.AddField(
            model_name='bike',
            name='accident_history',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bike',
            name='city',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='bike',
            name='engine_cc',
            field=models.IntegerField(blank=True, help_text='Engine capacity in CC', null=True),
        ),
        migrations.AddField(
            model_name='bike',
            name='insurance_validity',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bike',
            name='modifications',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bike',
            name='negotiable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='bike',
            name='ownership_number',
            field=models.IntegerField(default=1, help_text='Number of previous owners'),
        ),
        migrations.AddField(
            model_name='bike',
            name='registration_state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bike',
            name='seller',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bikes', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bike',
            name='service_history',
            field=models.BooleanField(default=False, help_text='Full service history available?'),
        ),
        migrations.AddField(
            model_name='bike',
            name='state',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='bike',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending review'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Sold', 'Sold'), ('Expired', 'Expired')], default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='bike',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='bike_videos/'),
        ),
        migrations.AddField(
            model_name='bike',
            name='warranty_remaining',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='BikeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='bike_images/')),
                ('bike', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='bikes.bike')),
            ],
        ),
    ]
